# Write a simulation instance out as Python, from the XML the real IOC is
# built from.
#
#     dls-va-ioc-sim generate .../SR03C-VA-IOC-01.xml 99
#     dls-va-ioc-sim generate .../SR21C-VA-IOC-01.xml 99 -o sr99c-scratch.py
#
# One file comes out, named after the IOC in lower case - sr99c-va-ioc-01.py -
# and it is the launcher as well as the instance.  A PEP 723 header names the
# version of this package that wrote it, a `uv run --script` shebang makes the
# file directly executable, and the Channel Access ports are set at the top of
# it, so ./sr99c-va-ioc-01.py builds its own environment and starts the IOC in
# it with nothing installed first.
#
# There used to be a shell script beside it - va-start-ioc, written by hand and
# then generated - holding the pythonSoftIOC to exec and the ports to serve on.
# Both of those now live in the instance, and pythonSoftIOC turns out to be
# twelve lines that Popen sys.executable on the script, so there is nothing
# left for a launcher to do.
#
# The point of generating a file rather than parsing at start up is that the
# file is the configuration: everything the XML declared is written out device
# by device, in the order a builder XML is in, ready to be read by someone who
# has never seen the XML and edited where the machine has a nuance the parse
# cannot know about.
#
# One thing is always left to be edited, and it is marked EDIT ME: the vacuum
# layout.  Nothing in a builder XML says which valve stands between which two
# lengths of pipe, how many litres a section holds or what it outgasses, so
# what is generated is one volume per domain, with no valve joining any of
# them and capacities and gas loads guessed from the installed pumping speed.
# It runs and it settles at a believable pressure; it is not the beam pipe.
#
# The generated file imports nothing from here.  It stands on the installed
# package alone, so editing it can never be undone by regenerating something
# else, and there is no template left to keep in step.

import os
import re
import sys

from ._version import __version__
from .builder_xml import GROUP_KINDS, parseXml
from .epics_ports import (
    CA_REPEATER_PORT,
    CA_SERVER_PORT,
    PVA_BROADCAST_PORT,
    PVA_SERVER_PORT,
)

# Device family -> the stem of the variable name generated for it.
FAMILY_NAMES = {
    "MPC": "mpc", "IONP": "ionp", "VALVE": "valve", "FVALV": "fvalve",
    "GCTLR": "gaugeSet", "GAUGE": "gauge", "IMG": "img", "PIRG": "pirg",
    "GIONP": "gionp", "GGAUG": "ggaug", "GIMG": "gimg", "GPIRG": "gpirg",
    "GVALV": "gvalv", "SPACE": "space",
}

# Group kind -> the class the generated file calls, and what it takes its
# members from.  A gauge group takes the gauge, an IMG group the gauge's img.
GROUP_CALLS = {
    "ionp": ("ionPumpGroupRecord", None),
    "gauge": ("gaugeGroupRecord", None),
    "img": ("imgGroupRecord", "img"),
    "pirg": ("pirgGroupRecord", "pirg"),
    "valve": ("valveGroupRecord", None),
}

DOMAIN_PATTERN = re.compile(r"^([A-Z]{2,3})(\d{2})(.*)$")

# HEADER and FOOTER are %-format templates, so every literal % in them has to
# be doubled.  The one that was not cost every generated instance its error
# reporting: `logging.exception("Simulation failed for %s", device.prefix)`
# came out of the substitution as "Simulation failed for {'volume': 'sr06s'}",
# because a bare %s takes the whole mapping.  That raises inside logging and
# loses the device name at exactly the moment a device has failed.

HEADER = '''#!/usr/bin/env -S uv run --script
# /// script
# requires-python = ">=3.11"
# dependencies = ["%(requirement)s"]
# ///
#
# Simulation of the vacuum in %(what)s.
#
# GENERATED by generate_ioc.py from
#   %(source)s
# and then edited by hand - regenerating overwrites this file, so keep a copy
# of anything worth keeping, or generate somewhere else and merge.
#
# This file is the IOC and its launcher both.  Run it:
#
#     ./%(instance)s          uv reads the header above, builds the
#     uv run %(instance)s     environment it asks for and starts the IOC in it
#     python %(instance)s     in any environment that already has the package
#
# Everything a PLC or a controller would decide - which valves may open, what
# a gauge pair reads, what the pressure is - is decided here instead, and
# served over Channel Access so that a screen or an archiver cannot tell it
# apart from the real thing.
#
%(report)s

import os

# Channel Access is served on a non-standard port, for the same reason the cell
# number in every device name is rewritten: a client looking for the real
# machine must never find this instead.  It is set here, before anything of
# softioc is imported, rather than by a wrapper script, so that there is no way
# to start this file on the real machine's port by forgetting something.
#
# The pvAccess ports are moved for the same reason.  This IOC serves no
# pvAccess at all - iocInit is called with enable_pva=False at the bottom of
# this file - but pythonSoftIOC would otherwise start a PVXS server beside the
# Channel Access one, offering every PV below under the same name on the
# standard port.  Moving the ports as well means that switching pvAccess back
# on cannot put a simulated storage ring on 5075.
#
# setdefault, so the environment still wins and a second simulation can run
# beside the first:
#
#     EPICS_CA_SERVER_PORT=%(otherPort)d EPICS_CA_REPEATER_PORT=%(otherRepeater)d \\
#         ./%(instance)s
os.environ.setdefault("EPICS_CA_SERVER_PORT", "%(serverPort)d")
os.environ.setdefault("EPICS_CA_REPEATER_PORT", "%(repeaterPort)d")
os.environ.setdefault("EPICS_PVAS_SERVER_PORT", "%(pvaPort)d")
os.environ.setdefault("EPICS_PVAS_BROADCAST_PORT", "%(pvaBroadcast)d")

import asyncio
import logging

from softioc import softioc, builder, asyncio_dispatcher

from dls_va_ioc_sim.builder_xml import attachLayout
from dls_va_ioc_sim.device_groups import orderedGroups
from dls_va_ioc_sim.fe_seq_records import valveGroupRecord, valveRecord
from dls_va_ioc_sim.gauge_records import (gaugeGroupRecord, gaugeSetRecord,
                                         imgGroupRecord, pirgGroupRecord)
from dls_va_ioc_sim.ion_pump_records import (ionPumpGroupRecord, ionPumpRecord,
                                           mpcRecord)
from dls_va_ioc_sim.vacuum_model import gate, vacuumLayout, vacuumVolume
from dls_va_ioc_sim.vacuum_space_records import spaceRecord

dispatcher = asyncio_dispatcher.AsyncioDispatcher()

# How often the simulated devices recalculate their readbacks.  One second
# matches the SCAN rate the real templates poll their hardware at.
SIMULATION_PERIOD = 1.0
'''

FOOTER = '''
# Everything the simulation has to step on a timer, in the order it has to be
# stepped in.  The vacuum layout comes first: it works out the pressures that
# the pumps and gauges then report in the same pass.  Groups read those, and a
# group of groups reads groups, which is what orderedGroups sorts out.  Spaces
# read the finished groups and so come last.
simulatedDevices = ([vacuum] + ionPumps + gaugeSets
                    + orderedGroups(vacuumGroups) + vacuumSpaces)

# Boilerplate to get the IOC started.
#
# enable_pva=False because pythonSoftIOC would otherwise start a PVXS/QSRV2
# server beside the Channel Access one, serving every record built above under
# its own name on the standard pvAccess port - where a client looking for the
# real machine would find it, whatever the Channel Access ports are set to.
builder.LoadDatabase()
softioc.iocInit(dispatcher, enable_pva=False)


async def simulate():
    """Step every simulated device on a fixed period, for as long as we run.

    The devices are taken from the module rather than passed in as arguments:
    the dispatcher hands extra arguments to the coroutine differently
    depending on the pythonSoftIOC version, and passing none at all behaves
    the same on both.
    """
    reported = set()
    while True:
        await asyncio.sleep(SIMULATION_PERIOD)
        for device in simulatedDevices:
            try:
                device.tick(SIMULATION_PERIOD)
            except Exception:
                # A dispatched coroutine that raises is dropped without a
                # word, which leaves the IOC up but every readback frozen.
                # Say so, once per device, and keep the others going.
                if device.prefix not in reported:
                    reported.add(device.prefix)
                    logging.exception("Simulation failed for %%s",
                                      device.prefix)


dispatcher(simulate)

# Finally leave the IOC running with an interactive shell.  The volumes are in
# scope there, which is where a leak is sprung now that none of the vacuum
# model is served:
#
#   >>> %(volume)s.gasLoad = 1.0e-4        a leak the pumps hold against
#   >>> %(volume)s.forcedPressure = 1e-3   pin it, and its group with it
#   >>> %(volume)s.forcedPressure = None   back to the model
softioc.interactive_ioc(globals())
'''


class names:
    """Readable, unique Python names for device prefixes.

    SR99A-VA-IONP-01 becomes ionpA01 and SR99C-VA-GIONP-01 gionpC01, so that
    a generated file reads like one written by hand and a device can still be
    found in it by eye from its PV name.
    """

    def __init__(self):
        self.byPrefix = {}
        self.taken = set()

    def of(self, prefix):
        if prefix in self.byPrefix:
            return self.byPrefix[prefix]

        parts = prefix.split("-")
        family = FAMILY_NAMES.get(parts[2] if len(parts) > 2 else "", "device")
        number = parts[3] if len(parts) > 3 else ""

        match = DOMAIN_PATTERN.match(parts[0])
        if match:
            area, _, suffix = match.groups()
            # SR is the storage ring and goes without saying; anything else
            # keeps its area, so SR99I and FE99I do not collide.
            tag = suffix if area == "SR" else area.capitalize() + suffix
        else:
            tag = parts[0]

        name = f"{family}{tag}{number}"
        candidate, serial = name, 2
        while candidate in self.taken:
            candidate, serial = f"{name}_{serial}", serial + 1

        self.taken.add(candidate)
        self.byPrefix[prefix] = candidate
        return candidate


def _gaugeOf(prefix):
    """SR99A-VA-IMG-01 -> SR99A-VA-GAUGE-01, the pair that owns the sensor."""
    parts = prefix.split("-")
    return "-".join(parts[:2] + ["GAUGE"] + parts[3:])


def _wrapped(opening, items, closing, indent=4, width=76):
    """One item per line if the whole thing will not fit on one."""
    single = opening + ", ".join(items) + closing
    if len(single) <= width:
        return [single]
    # The closing bracket lines up under whatever the opening was indented to,
    # not at the margin.
    base = " " * (len(opening) - len(opening.lstrip()))
    lines = [opening.rstrip()]
    pad = " " * indent
    line = pad
    for index, item in enumerate(items):
        piece = item + ("" if index == len(items) - 1 else ",")
        if len(line) + len(piece) + 1 > width and line.strip():
            lines.append(line.rstrip())
            line = pad
        line += piece + " "
    lines.append(line.rstrip())
    lines.append(base + closing.lstrip())
    return lines


def _comment(text, prefix="# "):
    return "\n".join(prefix + line if line else "#"
                     for line in text.splitlines())


def layoutSource(declarations, naming=None):
    """The vacuum layout section: one volume per domain, and no gates.

    This is the part of a builder XML that is not in a builder XML.  What is
    generated is somewhere to start that runs - every device on a volume, so
    nothing freezes, and a gas load that puts each domain at a believable
    pressure - not a description of the beam pipe.
    """
    naming = naming or names()
    lines = []
    volumes = []

    for domain in declarations.domains():
        guess = declarations.volumeGuess(domain)
        variable = domain.lower().replace("-", "_")
        volumes.append(variable)
        lines.append(f"{variable} = vacuumVolume(")
        lines.append(f'    "{domain}", litres={guess["litres"]:.1f}, '
                     f'gasLoad={guess["gasLoad"]:.2e},')
        lines.extend(_wrapped("    pumps=[", [f'"{p}"'
                                              for p in guess["pumps"]], "],",
                              indent=8))
        lines.extend(_wrapped("    gauges=[", [f'"{g}"'
                                               for g in guess["gauges"]], "])",
                              indent=8))
        lines.append("")

    lines.append("vacuum = vacuumLayout(")
    for index, variable in enumerate(volumes):
        lines.append(f"    {variable},")
        if index < len(volumes) - 1:
            lines.append("    # a gate() goes here if a valve joins these two")
    lines.append(")")
    lines.append("")
    lines.append("# The valves this IOC builds, none of them yet a gate:")
    for prefix in declarations.valves:
        lines.append(f'#     gate("{prefix}"),')
    return "\n".join(lines), volumes


def requirement():
    """The dependency a generated instance pins itself to, for its header.

    The version that generated it, so that an instance written today still
    starts when the framework has moved on - except from a checkout, where
    setuptools_scm gives something like 0.1.dev0+d20260811 that is on no index
    at all.  Pinning that would write a file that cannot resolve, so an
    unreleased generator asks for the package unpinned and whoever runs it
    gets the latest release.
    """
    if ".dev" in __version__ or "+" in __version__:
        return "dls-va-ioc-sim"
    return f"dls-va-ioc-sim=={__version__}"


def generate(declarations, iocName=None, instance=None):
    """Write the whole instance out as Python.

    `instance` is the filename it will be saved as, which the file names in
    its own header - the only thing in it that depends on where it is going.
    """
    naming = names()
    out = []

    if instance is None:
        instance = f"{(iocName or declarations.name).lower()}.py"

    out.append(HEADER % {
        "what": ("%s - one storage ring cell" % (iocName or declarations.name)),
        "source": declarations.source,
        "requirement": requirement(),
        "instance": instance,
        "serverPort": CA_SERVER_PORT,
        "repeaterPort": CA_REPEATER_PORT,
        "pvaPort": PVA_SERVER_PORT,
        "pvaBroadcast": PVA_BROADCAST_PORT,
        "otherPort": CA_SERVER_PORT + 2,
        "otherRepeater": CA_REPEATER_PORT + 2,
        "report": _comment(
            "What the XML said, and what was made of it.  Read this once:\n"
            "anything it could not place is listed here rather than dropped\n"
            "in silence.\n\n" + declarations.report())})

    # --- controllers and supplies -------------------------------------------
    out.append("""
# ---------------------------------------------------------------------------
# Ion pumps
#
# Each controller and the supplies on it, in the order the XML declares them,
# because a controller numbers its supplies as they are created.  Sizes and
# setpoints are the XML's, including any that look wrong.
# ---------------------------------------------------------------------------
""")
    for controller in declarations.controllers:
        out.append(f'{naming.of(controller.prefix)} = mpcRecord("{controller.prefix}")')
    out.append("")
    for pump in declarations.pumps:
        setpoints = ", ".join(f"{key}={pump.setpoints[key]:.1e}"
                              for key in ("sp1on", "sp1off", "sp2on", "sp2off"))
        out.append(f"{naming.of(pump.prefix)} = ionPumpRecord(")
        out.append(f'    {naming.of(pump.controller)}, "{pump.prefix}", '
                   f'pump={pump.pump}, size={pump.size}, '
                   f'strapping={pump.strapping},')
        out.append(f"    {setpoints})")
    out.append("")
    out.extend(_wrapped("ionPumps = [",
                        [naming.of(pump.prefix) for pump in declarations.pumps],
                        "]"))

    # --- gauges --------------------------------------------------------------
    out.append("""
# ---------------------------------------------------------------------------
# Gauges
#
# One MKS 937B per controller, each carrying up to two cold cathodes and two
# Piranis - a gauge pair on each of two lengths of pipe.  Relays are numbered
# across a controller in creation order, so the order here matters.
# ---------------------------------------------------------------------------
""")
    for gaugeSet in declarations.gaugeSets:
        arguments = f'"{gaugeSet.dom}", "{gaugeSet.setNumber}", idA="{gaugeSet.idA}"'
        if gaugeSet.idB:
            arguments += f', idB="{gaugeSet.idB}"'
        out.append(f"{naming.of(gaugeSet.prefix)} = gaugeSetRecord({arguments})")
    out.append("")
    for gaugeSet in declarations.gaugeSets:
        gauges = [naming.of(name) for name in gaugeSet.deviceNames("GAUGE")]
        if len(gauges) == 1:
            out.append(f"({gauges[0]},) = {naming.of(gaugeSet.prefix)}.gauges")
        else:
            out.append(f"{', '.join(gauges)} = "
                       f"{naming.of(gaugeSet.prefix)}.gauges")
    out.append("")
    out.extend(_wrapped("gaugeSets = [",
                        [naming.of(gaugeSet.prefix)
                         for gaugeSet in declarations.gaugeSets], "]"))
    out.append("")
    out.append("# The gauge pairs themselves - a gaugeSet is ticked, but it is")
    out.append("# the gauges on it that sit on a volume.")
    out.extend(_wrapped("gauges = [",
                        [naming.of(name)
                         for gaugeSet in declarations.gaugeSets
                         for name in gaugeSet.deviceNames("GAUGE")], "]"))

    # --- valves --------------------------------------------------------------
    out.append("""
# ---------------------------------------------------------------------------
# Valves
#
# Which of these stands in the beam pipe and which branches off it is not in
# the XML - it is decided in the vacuum layout below.
# ---------------------------------------------------------------------------
""")
    for prefix in declarations.valves:
        out.append(f'{naming.of(prefix)} = valveRecord("{prefix}")')

    # --- the layout ----------------------------------------------------------
    layout, volumes = layoutSource(declarations, naming)
    out.append("""
# ---------------------------------------------------------------------------
# The vacuum layout                                            *** EDIT ME ***
#
# None of this is served over Channel Access: it is the simulation's own model
# of the beam pipe, and no real IOC has a record for how many litres a section
# holds.
#
# *** This is generated as a guess and is almost certainly wrong. ***  The XML
# says which devices exist and which groups they are in; it says nothing about
# which valve stands between which two lengths of pipe, how many litres a
# section holds or what it outgasses.  On the real machine that comes off a
# P&ID.  What is below is one volume per domain, joined by nothing, with
# capacities from the number of supplies and gas loads chosen to settle each
# domain near 7e-10 mbar - enough to run, not enough to believe.
#
# To make it the machine:
#
#   * Split a domain where a valve really does divide it, and put a gate()
#     between the two halves.  A gate's neighbours are simply the entries
#     either side of it, so there is no second place for the topology to
#     disagree with itself.
#   * Leave a *branch* valve out.  A valve that goes off to a front end takes
#     a beamline off and leaves the ring's own gas where it was; it separates
#     nothing here and gets no gate entry.  So does a valve with pipe on only
#     one side of it.
#   * Give a volume the litres and the gas load it really has.  A volume
#     settles at gasLoad / speed, so those two numbers are its pressure.
#
# Every pump and gauge has to stay on some volume.  attachLayout refuses a
# layout that leaves one off, because a device with no volume raises on its
# first tick, the dispatcher swallows it, and the rest of that controller's
# gauges quietly stop updating.
# ---------------------------------------------------------------------------
""")
    out.append(layout)
    out.append("")
    out.extend(_wrapped("valves = [",
                        [naming.of(prefix) for prefix in declarations.valves],
                        "]"))
    out.append("")
    out.append("attachLayout(vacuum, ionPumps + gauges + valves)")

    # --- groups --------------------------------------------------------------
    out.append("""
# ---------------------------------------------------------------------------
# Groups
#
# A group stands for several devices at once, and its members may themselves
# be groups - one write to a cell level GIONP reaches every supply below it.
# They are in dependency order: a group is built after everything inside it,
# because it seeds its own records from its members'.
#
# The XML pads every group to eight slots by repeating a member; only the
# distinct ones are here.
# ---------------------------------------------------------------------------
""")
    groupNames = []
    groupPrefixes = {group.prefix for group in declarations.groups}
    for group in declarations.groups:
        call, attribute = GROUP_CALLS[group.kind]
        groupNames.append(naming.of(group.prefix))
        members = []
        for member in group.members:
            name = naming.of(member)
            # An IMG or PIRG group reaches its sensors through the gauge pair
            # that owns them - but a member that is itself a group is passed
            # as it stands, because a group publishes the same record names
            # its members do.
            if attribute and member not in groupPrefixes:
                name = f"{naming.of(_gaugeOf(member))}.{attribute}"
            members.append(name)
        out.append(f"{naming.of(group.prefix)} = {call}(")
        out.append(f'    "{group.prefix}",')
        out.extend(_wrapped("    [", members, "],", indent=8))
        out.append(f"    delay={group.delay:g})")
    out.append("")
    out.extend(_wrapped("vacuumGroups = [", groupNames, "]"))

    # --- spaces --------------------------------------------------------------
    out.append("""
# ---------------------------------------------------------------------------
# Vacuum spaces
#
# What an operator is shown: a pressure, a status lamp and the controls for a
# section of machine.  A space owns nothing - every record either reads one of
# its five groups or writes to one - so what it covers is decided entirely by
# which groups it is given.
# ---------------------------------------------------------------------------
""")
    out.append("vacuumSpaces = [")
    for space in declarations.spaces:
        out.append('    spaceRecord(')
        out.append(f'        "{space.prefix}",')
        for index, kind in enumerate(GROUP_KINDS):
            tail = ")," if index == len(GROUP_KINDS) - 1 else ","
            out.append(f"        {kind}={naming.of(space.groups[kind])}{tail}")
    out.append("]")

    out.append(FOOTER % {"volume": volumes[0] if volumes else "volume"})
    return "\n".join(out) + "\n"


def instancePath(declarations, output=None):
    """Where the instance goes.

    Named after the IOC in lower case - sr99c-va-ioc-01.py - and written into
    the current directory.  It used to land beside the generator, back when an
    instance had to sit in the one directory it could import the framework
    from; now that the framework is an installed package an instance can live
    wherever its IOC does.
    """
    if output is None:
        output = os.path.abspath(f"{declarations.name.lower()}.py")
    return output


def addArguments(parser):
    """The `generate` subcommand's arguments.  See __main__."""
    parser.add_argument("xml", help="the builder XML the real IOC is built "
                                    "from")
    parser.add_argument("cell", nargs="?", default="99",
                        help="the two digit cell to rename into, so the "
                             "simulation cannot be taken for the real "
                             "machine (default 99)")
    parser.add_argument("-o", "--output",
                        help="where to write the instance (default "
                             "<ioc name>.py in lower case, in the current "
                             "directory)")
    parser.add_argument("-f", "--force", action="store_true",
                        help="overwrite the output if it already exists")
    parser.add_argument("-n", "--dry-run", action="store_true",
                        help="report what the XML says and write nothing")
    return parser


def generateCommand(arguments, error=None):
    """Write the instance one builder XML asks for.  Returns an exit code.

    `error` is the parser's own error reporter, so that a bad cell number comes
    back as usage rather than as a traceback; without one it raises.
    """
    if not re.fullmatch(r"\d{2}", arguments.cell):
        message = "cell should be two digits, like 99"
        if error is None:
            raise ValueError(message)
        error(message)

    declarations = parseXml(arguments.xml, cell=arguments.cell)
    print(declarations.report(), file=sys.stderr)

    unrecognised = declarations.unrecognised()
    if unrecognised:
        print("\nthese tags were not recognised and nothing was made of "
              "them:\n  {}".format("\n  ".join(unrecognised)), file=sys.stderr)

    if arguments.dry_run:
        return 0

    output = instancePath(declarations, arguments.output)

    if os.path.exists(output) and not arguments.force:
        print(f"\n{output} exists already.  The instance may have been edited "
              "by hand, so nothing has been written - pass --force, or -o "
              "somewhere else.", file=sys.stderr)
        return 1

    with open(output, "w") as handle:
        handle.write(generate(declarations, instance=os.path.basename(output)))
    # The instance is its own launcher, so it has to be runnable.
    os.chmod(output, 0o755)
    print(f"\nwrote {output}", file=sys.stderr)
    return 0
