# Simulation of the vacuum in SR99C-VA-IOC-01 - one storage ring cell.
#
# GENERATED by generateIoc.py from
#   /dls_sw/work/R3.14.12.7/support/jjc62351/support/SR-BUILDER/etc/makeIocs/SR03C-VA-IOC-01.xml
# and then edited by hand - regenerating overwrites this file, so keep a copy
# of anything worth keeping, or generate somewhere else and merge.
#
# Everything a PLC or a controller would decide - which valves may open, what
# a gauge pair reads, what the pressure is - is decided here instead, and
# served over Channel Access so that a screen or an archiver cannot tell it
# apart from the real thing.
#
# What the XML said, and what was made of it.  Read this once:
# anything it could not place is listed here rather than dropped
# in silence.
#
# SR99C-VA-IOC-01  (from /dls_sw/work/R3.14.12.7/support/jjc62351/support/SR-BUILDER/etc/makeIocs/SR03C-VA-IOC-01.xml)
#   found    18 ion pumps on 9 controllers
#            8 gauge pairs on 4 controllers
#            4 valves, 17 groups, 3 spaces
#   dropped
#            SR99C-VA-GIONP-01 member SR99I-VA-GIONP-01 not built here - it belongs to another IOC
#            SR99C-VA-GGAUG-01 member SR99I-VA-GGAUG-01 not built here - it belongs to another IOC
#            SR99C-VA-GIMG-01 member SR99I-VA-GIMG-01 not built here - it belongs to another IOC
#            SR99C-VA-GPIRG-01 member SR99I-VA-GPIRG-01 not built here - it belongs to another IOC
#   ignored
#            EPICS_BASE.EpicsEnvSet               x4    IOC and rack housekeeping
#            FINS.FINSUDPInit                     x1    a link to hardware that is not here
#            SR-VA.common                         x1    IOC and rack housekeeping
#            asyn.AsynIP                          x16   a link to hardware that is not here
#            autosave.Autosave                    x1    IOC and rack housekeeping
#            digitelMpc.digitelMpcTspGroup        x1    no TSP class
#            dlsPLC.NX102_readBool                x1    PLC glue, no PLC here
#            dlsPLC.NX102_readReal                x2    PLC glue, no PLC here
#            dlsPLC.fastVacuumChannel             x8    fast vacuum detection, no class
#            dlsPLC.fastVacuumMaster              x1    fast vacuum detection, no class
#            ether_ip.EtherIPInit                 x1    a link to hardware that is not here
#            mks937a.mks937aGaugeEGU              x2    an EGU conversion on a gauge already built
#            mks937a.mks937aImgMean               x4    beam desorption average, not a space device
#            rga.rga                              x6    no RGA class
#            rga.rgaGroup                         x1    no RGA class

import asyncio
import logging
from softioc import softioc, builder, asyncio_dispatcher

from dls_va_ioc_sim.builder_xml import attachLayout
from dls_va_ioc_sim.device_groups import orderedGroups
from dls_va_ioc_sim.fe_seq_records import valveGroupRecord, valveRecord
from dls_va_ioc_sim.gauge_records import (
    gaugeGroupRecord,
    gaugeSetRecord,
    imgGroupRecord,
    pirgGroupRecord,
)
from dls_va_ioc_sim.ion_pump_records import ionPumpGroupRecord, ionPumpRecord, mpcRecord
from dls_va_ioc_sim.vacuum_model import gate, vacuumLayout, vacuumVolume
from dls_va_ioc_sim.vacuum_space_records import spaceRecord

dispatcher = asyncio_dispatcher.AsyncioDispatcher()

# How often the simulated devices recalculate their readbacks.  One second
# matches the SCAN rate the real templates poll their hardware at.
SIMULATION_PERIOD = 1.0


# ---------------------------------------------------------------------------
# Ion pumps
#
# Each controller and the supplies on it, in the order the XML declares them,
# because a controller numbers its supplies as they are created.  Sizes and
# setpoints are the XML's, including any that look wrong.
# ---------------------------------------------------------------------------

mpcS01 = mpcRecord("SR99S-VA-MPC-01")
mpcA01 = mpcRecord("SR99A-VA-MPC-01")
mpcA02 = mpcRecord("SR99A-VA-MPC-02")
mpcA03 = mpcRecord("SR99A-VA-MPC-03")
mpcA04 = mpcRecord("SR99A-VA-MPC-04")
mpcA05 = mpcRecord("SR99A-VA-MPC-05")
mpcA06 = mpcRecord("SR99A-VA-MPC-06")
mpcA07 = mpcRecord("SR99A-VA-MPC-07")
mpcA08 = mpcRecord("SR99A-VA-MPC-08")

ionpS01 = ionPumpRecord(
    mpcS01,
    "SR99S-VA-IONP-01",
    pump=1,
    size=300,
    strapping=7000,
    sp1on=1.0e-10,
    sp1off=1.0e-04,
    sp2on=1.0e-10,
    sp2off=1.0e-04,
)
ionpS03 = ionPumpRecord(
    mpcS01,
    "SR99S-VA-IONP-03",
    pump=2,
    size=300,
    strapping=7000,
    sp1on=1.0e-08,
    sp1off=2.0e-08,
    sp2on=1.0e-08,
    sp2off=2.0e-08,
)
ionpA01 = ionPumpRecord(
    mpcA01,
    "SR99A-VA-IONP-01",
    pump=1,
    size=300,
    strapping=7000,
    sp1on=1.0e-10,
    sp1off=1.0e-04,
    sp2on=1.0e-10,
    sp2off=1.0e-04,
)
ionpA02 = ionPumpRecord(
    mpcA01,
    "SR99A-VA-IONP-02",
    pump=2,
    size=300,
    strapping=7000,
    sp1on=1.0e-10,
    sp1off=1.0e-04,
    sp2on=1.0e-10,
    sp2off=1.0e-04,
)
ionpA03 = ionPumpRecord(
    mpcA02,
    "SR99A-VA-IONP-03",
    pump=1,
    size=300,
    strapping=7000,
    sp1on=1.0e-10,
    sp1off=1.0e-04,
    sp2on=1.0e-10,
    sp2off=1.0e-04,
)
ionpA04 = ionPumpRecord(
    mpcA02,
    "SR99A-VA-IONP-04",
    pump=2,
    size=500,
    strapping=7000,
    sp1on=1.0e-10,
    sp1off=1.0e-04,
    sp2on=1.0e-10,
    sp2off=1.0e-04,
)
ionpA05 = ionPumpRecord(
    mpcA03,
    "SR99A-VA-IONP-05",
    pump=1,
    size=500,
    strapping=7000,
    sp1on=1.0e-08,
    sp1off=2.0e-08,
    sp2on=1.0e-08,
    sp2off=2.0e-08,
)
ionpA06 = ionPumpRecord(
    mpcA03,
    "SR99A-VA-IONP-06",
    pump=2,
    size=500,
    strapping=7000,
    sp1on=1.0e-10,
    sp1off=1.0e-04,
    sp2on=1.0e-10,
    sp2off=1.0e-04,
)
ionpA07 = ionPumpRecord(
    mpcA04,
    "SR99A-VA-IONP-07",
    pump=1,
    size=300,
    strapping=7000,
    sp1on=1.0e-10,
    sp1off=1.0e-04,
    sp2on=1.0e-10,
    sp2off=1.0e-04,
)
ionpA08 = ionPumpRecord(
    mpcA04,
    "SR99A-VA-IONP-08",
    pump=2,
    size=300,
    strapping=7000,
    sp1on=1.0e-10,
    sp1off=1.0e-04,
    sp2on=1.0e-10,
    sp2off=1.0e-04,
)
ionpA09 = ionPumpRecord(
    mpcA06,
    "SR99A-VA-IONP-09",
    pump=1,
    size=300,
    strapping=7000,
    sp1on=1.0e-10,
    sp1off=1.0e-04,
    sp2on=1.0e-10,
    sp2off=1.0e-04,
)
ionpA10 = ionPumpRecord(
    mpcA05,
    "SR99A-VA-IONP-10",
    pump=1,
    size=300,
    strapping=7000,
    sp1on=1.0e-10,
    sp1off=1.0e-04,
    sp2on=1.0e-10,
    sp2off=1.0e-04,
)
ionpA11 = ionPumpRecord(
    mpcA06,
    "SR99A-VA-IONP-11",
    pump=2,
    size=500,
    strapping=7000,
    sp1on=1.0e-10,
    sp1off=1.0e-04,
    sp2on=1.0e-10,
    sp2off=1.0e-04,
)
ionpA12 = ionPumpRecord(
    mpcA05,
    "SR99A-VA-IONP-12",
    pump=2,
    size=500,
    strapping=7000,
    sp1on=1.0e-08,
    sp1off=2.0e-08,
    sp2on=1.0e-08,
    sp2off=2.0e-08,
)
ionpA13 = ionPumpRecord(
    mpcA07,
    "SR99A-VA-IONP-13",
    pump=1,
    size=500,
    strapping=7000,
    sp1on=1.0e-10,
    sp1off=1.0e-04,
    sp2on=1.0e-10,
    sp2off=1.0e-04,
)
ionpA14 = ionPumpRecord(
    mpcA07,
    "SR99A-VA-IONP-14",
    pump=2,
    size=300,
    strapping=7000,
    sp1on=1.0e-10,
    sp1off=1.0e-04,
    sp2on=1.0e-10,
    sp2off=1.0e-04,
)
ionpA15 = ionPumpRecord(
    mpcA08,
    "SR99A-VA-IONP-15",
    pump=1,
    size=300,
    strapping=7000,
    sp1on=1.0e-10,
    sp1off=1.0e-04,
    sp2on=1.0e-10,
    sp2off=1.0e-04,
)
ionpA16 = ionPumpRecord(
    mpcA08,
    "SR99A-VA-IONP-16",
    pump=2,
    size=300,
    strapping=7000,
    sp1on=1.0e-08,
    sp1off=2.0e-08,
    sp2on=1.0e-08,
    sp2off=2.0e-08,
)

ionPumps = [
    ionpS01,
    ionpS03,
    ionpA01,
    ionpA02,
    ionpA03,
    ionpA04,
    ionpA05,
    ionpA06,
    ionpA07,
    ionpA08,
    ionpA09,
    ionpA10,
    ionpA11,
    ionpA12,
    ionpA13,
    ionpA14,
    ionpA15,
    ionpA16,
]

# ---------------------------------------------------------------------------
# Gauges
#
# One MKS 937B per controller, each carrying up to two cold cathodes and two
# Piranis - a gauge pair on each of two lengths of pipe.  Relays are numbered
# across a controller in creation order, so the order here matters.
# ---------------------------------------------------------------------------

gaugeSetS01 = gaugeSetRecord("SR99S", "01", idA="01", idB="02")
gaugeSetA01 = gaugeSetRecord("SR99A", "01", idA="01", idB="02")
gaugeSetA02 = gaugeSetRecord("SR99A", "02", idA="71", idB="03")
gaugeSetA03 = gaugeSetRecord("SR99A", "03", idA="31", idB="04")

gaugeS01, gaugeS02 = gaugeSetS01.gauges
gaugeA01, gaugeA02 = gaugeSetA01.gauges
gaugeA71, gaugeA03 = gaugeSetA02.gauges
gaugeA31, gaugeA04 = gaugeSetA03.gauges

gaugeSets = [gaugeSetS01, gaugeSetA01, gaugeSetA02, gaugeSetA03]

# The gauge pairs themselves - a gaugeSet is ticked, but it is
# the gauges on it that sit on a volume.
gauges = [
    gaugeS01,
    gaugeS02,
    gaugeA01,
    gaugeA02,
    gaugeA71,
    gaugeA03,
    gaugeA31,
    gaugeA04,
]

# ---------------------------------------------------------------------------
# Valves
#
# Which of these stands in the beam pipe and which branches off it is not in
# the XML - it is decided in the vacuum layout below.
# ---------------------------------------------------------------------------

valveA01 = valveRecord("SR99A-VA-VALVE-01")
valveA02 = valveRecord("SR99A-VA-VALVE-02")
valveA03 = valveRecord("SR99A-VA-VALVE-03")
valveA04 = valveRecord("SR99A-VA-VALVE-04")

# ---------------------------------------------------------------------------
# The vacuum layout                                            *** EDIT ME ***
#
# None of this is served over Channel Access: it is the simulation's own model
# of the beam pipe, and no real IOC has a record for how many litres a section
# holds.
#
# *** This is generated as a guess and is almost certainly wrong. ***  The XML
# says which devices exist and which groups they are in; it says nothing about
# which valve stands between which two lengths of pipe, how many litres a
# section holds or what it outgasses.  On the real machine that comes off a
# P&ID.  What is below is one volume per domain, joined by nothing, with
# capacities from the number of supplies and gas loads chosen to settle each
# domain near 7e-10 mbar - enough to run, not enough to believe.
#
# To make it the machine:
#
#   * Split a domain where a valve really does divide it, and put a gate()
#     between the two halves.  A gate's neighbours are simply the entries
#     either side of it, so there is no second place for the topology to
#     disagree with itself.
#   * Leave a *branch* valve out.  A valve that goes off to a front end takes
#     a beamline off and leaves the ring's own gas where it was; it separates
#     nothing here and gets no gate entry.  So does a valve with pipe on only
#     one side of it.
#   * Give a volume the litres and the gas load it really has.  A volume
#     settles at gasLoad / speed, so those two numbers are its pressure.
#
# Every pump and gauge has to stay on some volume.  attachLayout refuses a
# layout that leaves one off, because a device with no volume raises on its
# first tick, the dispatcher swallows it, and the rest of that controller's
# gauges quietly stop updating.
# ---------------------------------------------------------------------------

sr99s = vacuumVolume(
    "SR99S",
    litres=10.0,
    gasLoad=4.20e-07,
    pumps=["SR99S-VA-IONP-01", "SR99S-VA-IONP-03"],
    gauges=["SR99S-VA-GAUGE-01", "SR99S-VA-GAUGE-02"],
)

sr99a = vacuumVolume(
    "SR99A",
    litres=40.0,
    gasLoad=4.20e-06,
    pumps=[
        "SR99A-VA-IONP-01",
        "SR99A-VA-IONP-02",
        "SR99A-VA-IONP-03",
        "SR99A-VA-IONP-04",
        "SR99A-VA-IONP-05",
        "SR99A-VA-IONP-06",
        "SR99A-VA-IONP-07",
        "SR99A-VA-IONP-08",
        "SR99A-VA-IONP-09",
        "SR99A-VA-IONP-10",
        "SR99A-VA-IONP-11",
        "SR99A-VA-IONP-12",
        "SR99A-VA-IONP-13",
        "SR99A-VA-IONP-14",
        "SR99A-VA-IONP-15",
        "SR99A-VA-IONP-16",
    ],
    gauges=[
        "SR99A-VA-GAUGE-01",
        "SR99A-VA-GAUGE-02",
        "SR99A-VA-GAUGE-71",
        "SR99A-VA-GAUGE-03",
        "SR99A-VA-GAUGE-31",
        "SR99A-VA-GAUGE-04",
    ],
)

vacuum = vacuumLayout(
    sr99s,
    # a gate() goes here if a valve joins these two
    sr99a,
)

# The valves this IOC builds, none of them yet a gate:
#     gate("SR99A-VA-VALVE-01"),
#     gate("SR99A-VA-VALVE-02"),
#     gate("SR99A-VA-VALVE-03"),
#     gate("SR99A-VA-VALVE-04"),

valves = [valveA01, valveA02, valveA03, valveA04]

attachLayout(vacuum, ionPumps + gauges + valves)

# ---------------------------------------------------------------------------
# Groups
#
# A group stands for several devices at once, and its members may themselves
# be groups - one write to a cell level GIONP reaches every supply below it.
# They are in dependency order: a group is built after everything inside it,
# because it seeds its own records from its members'.
#
# The XML pads every group to eight slots by repeating a member; only the
# distinct ones are here.
# ---------------------------------------------------------------------------

gionpS01 = ionPumpGroupRecord("SR99S-VA-GIONP-01", [ionpS01, ionpS03], delay=2)
gionpA02 = ionPumpGroupRecord(
    "SR99A-VA-GIONP-02",
    [ionpA01, ionpA02, ionpA03, ionpA04, ionpA05, ionpA06, ionpA07, ionpA08],
    delay=10,
)
gionpA03 = ionPumpGroupRecord(
    "SR99A-VA-GIONP-03",
    [ionpA09, ionpA10, ionpA11, ionpA12, ionpA13, ionpA14, ionpA15, ionpA16],
    delay=10,
)
gionpA01 = ionPumpGroupRecord("SR99A-VA-GIONP-01", [gionpA02, gionpA03], delay=20)
gionpC01 = ionPumpGroupRecord("SR99C-VA-GIONP-01", [gionpA01, gionpS01], delay=26)
ggaugS01 = gaugeGroupRecord("SR99S-VA-GGAUG-01", [gaugeS01, gaugeS02], delay=0)
ggaugA01 = gaugeGroupRecord(
    "SR99A-VA-GGAUG-01", [gaugeA01, gaugeA02, gaugeA03, gaugeA04, gaugeA31], delay=0
)
ggaugC01 = gaugeGroupRecord("SR99C-VA-GGAUG-01", [ggaugS01, ggaugA01], delay=0)
gimgS01 = imgGroupRecord("SR99S-VA-GIMG-01", [gaugeS01.img, gaugeS02.img], delay=0)
gimgA01 = imgGroupRecord(
    "SR99A-VA-GIMG-01",
    [gaugeA01.img, gaugeA02.img, gaugeA03.img, gaugeA04.img, gaugeA31.img],
    delay=0,
)
gimgC01 = imgGroupRecord("SR99C-VA-GIMG-01", [gimgS01, gimgA01], delay=0)
gpirgS01 = pirgGroupRecord("SR99S-VA-GPIRG-01", [gaugeS01.pirg, gaugeS02.pirg], delay=0)
gpirgA01 = pirgGroupRecord(
    "SR99A-VA-GPIRG-01",
    [gaugeA01.pirg, gaugeA02.pirg, gaugeA03.pirg, gaugeA04.pirg, gaugeA31.pirg],
    delay=0,
)
gpirgC01 = pirgGroupRecord("SR99C-VA-GPIRG-01", [gpirgS01, gpirgA01], delay=0)
gvalvS01 = valveGroupRecord("SR99S-VA-GVALV-01", [valveA01], delay=0)
gvalvA01 = valveGroupRecord(
    "SR99A-VA-GVALV-01", [valveA02, valveA03, valveA01, valveA04], delay=5
)
gvalvC01 = valveGroupRecord("SR99C-VA-GVALV-01", [gvalvA01, gvalvS01], delay=5)

vacuumGroups = [
    gionpS01,
    gionpA02,
    gionpA03,
    gionpA01,
    gionpC01,
    ggaugS01,
    ggaugA01,
    ggaugC01,
    gimgS01,
    gimgA01,
    gimgC01,
    gpirgS01,
    gpirgA01,
    gpirgC01,
    gvalvS01,
    gvalvA01,
    gvalvC01,
]

# ---------------------------------------------------------------------------
# Vacuum spaces
#
# What an operator is shown: a pressure, a status lamp and the controls for a
# section of machine.  A space owns nothing - every record either reads one of
# its five groups or writes to one - so what it covers is decided entirely by
# which groups it is given.
# ---------------------------------------------------------------------------

vacuumSpaces = [
    spaceRecord(
        "SR99S-VA-SPACE-01",
        ionp=gionpS01,
        gauge=ggaugS01,
        img=gimgS01,
        pirg=gpirgS01,
        valve=gvalvS01,
    ),
    spaceRecord(
        "SR99A-VA-SPACE-01",
        ionp=gionpA01,
        gauge=ggaugA01,
        img=gimgA01,
        pirg=gpirgA01,
        valve=gvalvA01,
    ),
    spaceRecord(
        "SR99C-VA-SPACE-01",
        ionp=gionpC01,
        gauge=ggaugC01,
        img=gimgC01,
        pirg=gpirgC01,
        valve=gvalvC01,
    ),
]

# Everything the simulation has to step on a timer, in the order it has to be
# stepped in.  The vacuum layout comes first: it works out the pressures that
# the pumps and gauges then report in the same pass.  Groups read those, and a
# group of groups reads groups, which is what orderedGroups sorts out.  Spaces
# read the finished groups and so come last.
simulatedDevices = (
    [vacuum] + ionPumps + gaugeSets + orderedGroups(vacuumGroups) + vacuumSpaces
)

# Boilerplate to get the IOC started
builder.LoadDatabase()
softioc.iocInit(dispatcher)


async def simulate():
    """Step every simulated device on a fixed period, for as long as we run.

    The devices are taken from the module rather than passed in as arguments:
    the dispatcher hands extra arguments to the coroutine differently
    depending on the pythonSoftIOC version, and passing none at all behaves
    the same on both.
    """
    reported = set()
    while True:
        await asyncio.sleep(SIMULATION_PERIOD)
        for device in simulatedDevices:
            try:
                device.tick(SIMULATION_PERIOD)
            except Exception:
                # A dispatched coroutine that raises is dropped without a
                # word, which leaves the IOC up but every readback frozen.
                # Say so, once per device, and keep the others going.
                if device.prefix not in reported:
                    reported.add(device.prefix)
                    logging.exception(
                        "Simulation failed for {'volume': 'sr99s'}", device.prefix
                    )


dispatcher(simulate)

# Finally leave the IOC running with an interactive shell.  The volumes are in
# scope there, which is where a leak is sprung now that none of the vacuum
# model is served:
#
#   >>> sr99s.gasLoad = 1.0e-4        a leak the pumps hold against
#   >>> sr99s.forcedPressure = 1e-3   pin it, and its group with it
#   >>> sr99s.forcedPressure = None   back to the model
softioc.interactive_ioc(globals())
